### ISSUE TITLE
Draw Resize Overlay around transformed objects

### ISSUE THREAD

**Issue by jogibear9988** [node-projects/web-component-designer#90]
Check how we could draw the resize/selection overlay around a rotated object (or otherwise transformed)

- [x] try to draw the lines without 1px x 1px helper div... use matrix transform. Consider transform origin in tx and ty. Remove helper element's 1px/1px cornerDiv if successful.
- [x] Consider scale factor > done with 9e44aeb8a29320713af3075482de64e2b7e0e999
- [x] Redraw while scolling canvas > not necessary
- [x] overlay doesn't fit perfectly in all rotation angles > Fixed with 3dc7c24ec688e655212a2798cdfffca4dd5b1e79
- [x] When an object is dragged into another, the overlay is drawn in the wrong place
- [x] Restore mouse extension over after placement > 2227ac9517054441939d0bd30888e3cd5db7bb6f
- [x] Consider parent rotation

**Comment by 7evenk** [comment]
### How does the helperElement / cornerDiv variant work?

![image](https://user-images.githubusercontent.com/5232626/196808673-87632188-907a-4d56-ae90-67f4198eb054.png)

A clone of the actual element for which the vertices are to be determined is also passed to the method. 
The visibility is set to hidden for this element. At the same time the current transform is saved and reset. Then the clone is added to the DOM (helperElement) located in designerCanvas. 

![image](https://user-images.githubusercontent.com/5232626/196808971-680ed913-af11-47ed-b4ec-d86b2ab150a0.png)

The Transform Origin of the cloned element without transformation is saved.
Then the cloned element is destroyed.

![image](https://user-images.githubusercontent.com/5232626/196809001-451882e7-8090-457f-85a6-7013d0ef5a9d.png)

**Calculate corner points of the untransformed element and store them in an object array**

`  const cornerPoints: IPoint[] = [
    {
      x: originalRect.x + cloneBoundingRect.x - untransformedCornerPointsOffset,
      y: originalRect.y + cloneBoundingRect.y - untransformedCornerPointsOffset
    },
    {
      x: originalRect.x + cloneBoundingRect.x + cloneBoundingRect.width + untransformedCornerPointsOffset,
      y: originalRect.y + cloneBoundingRect.y - untransformedCornerPointsOffset
    },
    {
      x: originalRect.x + cloneBoundingRect.x - untransformedCornerPointsOffset,
      y: originalRect.y + cloneBoundingRect.y + cloneBoundingRect.height + untransformedCornerPointsOffset
    },
    {
      x: originalRect.x + cloneBoundingRect.x + cloneBoundingRect.width + untransformedCornerPointsOffset,
      y: originalRect.y + cloneBoundingRect.y + cloneBoundingRect.height + untransformedCornerPointsOffset
    }
  ]
`

_Is the original rect needed at all?
The element is located in the DesignerCanvas.
X and y apparently always return 0 anyway._


Remove helperElements‘s children
![image](https://user-images.githubusercontent.com/5232626/196809310-88e0db7b-833c-4662-ab23-9444274fdbfe.png)

` 
let cornerPointsTranformOrigins = new Array(4);
`

**Calculate transform origin of the corner points so that they are congruent with the transform origin of the element.**

`    const transformOrigin = (parseInt(transformOriginBackup.split(' ')[0]) + untransformedCornerPointsOffset).toString() + ' ' + (parseInt(transformOriginBackup.split(' ')[1]) + untransformedCornerPointsOffset).toString();
  cornerPointsTranformOrigins[0] = (parseInt(transformOrigin.split(' ')[0])).toString() + ' ' + (parseInt(transformOrigin.split(' ')[1])).toString();
  cornerPointsTranformOrigins[1] = (cornerPoints[0].x - cornerPoints[1].x + parseInt(transformOrigin.split(' ')[0])).toString() + ' ' + (parseInt(transformOrigin.split(' ')[1])).toString();
  cornerPointsTranformOrigins[2] = (parseInt(transformOrigin.split(' ')[0])).toString() + ' ' + (cornerPoints[0].y - cornerPoints[2].y + parseInt(transformOrigin.split(' ')[1])).toString();
  cornerPointsTranformOrigins[3] = (cornerPoints[0].x - cornerPoints[1].x + parseInt(transformOrigin.split(' ')[0])).toString() + ' ' + (cornerPoints[0].y - cornerPoints[2].y + parseInt(transformOrigin.split(' ')[1])).toString();
`
![image](https://user-images.githubusercontent.com/5232626/196809771-a22d0241-9f43-4ff8-b612-ed4c610f221a.png)

**Create 1px/1px corner divs**

![image](https://user-images.githubusercontent.com/5232626/196809837-98fc6c56-653d-4a60-bb8f-716668ed893e.png)

` 
  const cornerDivs: HTMLDivElement[] = [];
  let element: HTMLDivElement;
  for (let i = 0; i < cornerPointsTranformOrigins.length; i++) {
    element = document.createElement('div');
    element.style.visibility = 'hidden';
    element.style.position = 'absolute';
    element.style.width = "1px";
    element.style.height = "1px";
    element.style.top = cornerPoints[i].y.toString() + 'px';
    element.style.left = cornerPoints[i].x.toString() + 'px';
    element.style.transformOrigin = cornerPointsTranformOrigins[i].split(' ')[0] + 'px' + ' ' + cornerPointsTranformOrigins[i].split(' ')[1] + 'px';
    cornerDivs.push(helperElement.appendChild(element));
  }
`

**Apply saved transform to the corner divs and calc their x and y values **

`  let transformedCornerPoints: IPoint3D[] = [];
	for (let i = 0; i < cornerDivs.length; i++) {
    //let transformedCornerDiv: HTMLElement;
    let transformedCornerPoint: IPoint3D = { x: null, y: null, z: null };
    //transformedCornerDiv = applyMatrixToElement((<HTMLElement>this.extendedItem.element).style.transform, cornerDivs[i]);
    cornerDivs[i].style.transform = transformBackup;
    //transformedCornerDiv =  applyMatrixToElement((<HTMLElement>this.extendedItem.element).style.transform, cornerDivs[i]);
    transformedCornerPoint.x = designerCanvas.getNormalizedElementCoordinates(cornerDivs[i]).x;
    transformedCornerPoint.y = designerCanvas.getNormalizedElementCoordinates(cornerDivs[i]).y;
    transformedCornerPoint.z = 0;
    transformedCornerPoints.push(transformedCornerPoint);
  }
return transformedCornerPoints;
`

**Comment by 7evenk** [comment]
### This is the new method without cornerDiv!

![image](https://user-images.githubusercontent.com/5232626/196810678-05dce422-0ecd-42b1-ae00-2bf95b48e661.png)

- Hide clone
- Reset transfrom
- Append clone to DOM (designerCanvas helperElement) 
- Destroy clone

![image](https://user-images.githubusercontent.com/5232626/196810788-8a51e8f8-0e55-4111-8ca6-2bce8745c638.png)

**Calculate the corner points of the untransformed clone**

`  const appendedCloneWithoutTranformCornerDOMPoints: DOMPoint[] = [];
  appendedCloneWithoutTranformCornerDOMPoints[topleft] = DOMPoint.fromPoint(
    {
      x: appendedCloneWithoutTranformRect.x - untransformedCornerPointsOffset,
      y: appendedCloneWithoutTranformRect.y - untransformedCornerPointsOffset
    }
  )

...

helperElement.replaceChildren();
`

**Calculate the transform origin related to the canvas**

![image](https://user-images.githubusercontent.com/5232626/196811125-006a6748-fed7-4a25-9d98-d597ebefff5a.png)

`  const transformOriginRelatedToCanvas: DOMPointReadOnly = DOMPointReadOnly.fromPoint(
    {
      x: appendedCloneWithoutTranformRect.x + parseInt(getComputedStyle(<HTMLElement>originalElement).transformOrigin.split(' ')[0]),
      y: appendedCloneWithoutTranformRect.y + parseInt(getComputedStyle(<HTMLElement>originalElement).transformOrigin.split(' ')[1]),
      z: 0,
      w: 0
    }
  )
`

**Calcluate the vectors (𝑻𝑶𝑷𝟎) ⃗,  (𝑻𝑶𝑷𝟏) ⃗,  (𝑻𝑶𝑷𝟐) ⃗,  (𝑻𝑶𝑷𝟑) ⃗**

`  
let top0 = new DOMPoint(-(transformOriginRelatedToCanvas.x - appendedCloneWithoutTranformCornerDOMPoints[topleft].x), -(transformOriginRelatedToCanvas.y - appendedCloneWithoutTranformCornerDOMPoints[topleft].y));
  let top1 = new DOMPoint(-(transformOriginRelatedToCanvas.x - appendedCloneWithoutTranformCornerDOMPoints[topright].x), -(transformOriginRelatedToCanvas.y - appendedCloneWithoutTranformCornerDOMPoints[topright].y));
  let top2 = new DOMPoint(-(transformOriginRelatedToCanvas.x - appendedCloneWithoutTranformCornerDOMPoints[bottomleft].x), -(transformOriginRelatedToCanvas.y - appendedCloneWithoutTranformCornerDOMPoints[bottomleft].y));
  let top3 = new DOMPoint(-(transformOriginRelatedToCanvas.x - appendedCloneWithoutTranformCornerDOMPoints[bottomright].x), -(transformOriginRelatedToCanvas.y - appendedCloneWithoutTranformCornerDOMPoints[bottomright].y));
`

**Apply original element‘s transformation matrix to each point**

`  let top0Transformed = top0.matrixTransform(originalElementMatrix);
  let top1Transformed = top1.matrixTransform(originalElementMatrix);
  let top2Transformed = top2.matrixTransform(originalElementMatrix);
  let top3Transformed = top3.matrixTransform(originalElementMatrix);
`

**Calcluate the vectors (𝑪𝑶𝑷𝟎′) ⃗,  (𝑪𝑶𝑷𝟏′) ⃗,  (𝑪𝑶𝑷𝟐′) ⃗,  (𝑪𝑶𝑷𝟑′) ⃗**

![image](https://user-images.githubusercontent.com/5232626/196811490-717110ae-7a86-4e64-a7bc-f84048750ee8.png)

`  let transformedCornerPoints: DOMPoint[] = [];
  transformedCornerPoints[0] = new DOMPoint(transformOriginRelatedToCanvas.x + top0Transformed.x, transformOriginRelatedToCanvas.y + top0Transformed.y);
  transformedCornerPoints[1] = new DOMPoint(transformOriginRelatedToCanvas.x + top1Transformed.x, transformOriginRelatedToCanvas.y + top1Transformed.y);
  transformedCornerPoints[2] = new DOMPoint(transformOriginRelatedToCanvas.x + top2Transformed.x, transformOriginRelatedToCanvas.y + top2Transformed.y);
  transformedCornerPoints[3] = new DOMPoint(transformOriginRelatedToCanvas.x + top3Transformed.x, transformOriginRelatedToCanvas.y + top3Transformed.y);
`

![image](https://user-images.githubusercontent.com/5232626/196811637-f76e7c84-ef83-4f17-976d-8466209311a8.png)

**Comment by 7evenk** [comment]
### Get original element’s transform origin relative to canvas and add available vectors to get the transformed corner points
```typescript
getDesignerCanvasNormalizedTransformedOrigin()
```

![image](https://user-images.githubusercontent.com/5232626/201710736-506f7a5a-9cc5-4d9d-bd47-81a9634de1f0.png)

1. Apply resulting transformation (multiplied self by all ancestors) to appendedClone.
2. Calc transform origin position related to designer canvas
3. Calc the element’s transform origin corner point vectors of the untransformed appendedClone
4. Apply the resulting transformation to all corner point vectors
5. Add these transformed vectors to original element’s transform origin that is related to the designer canvas

**Comment by 7evenk** [comment]
https://user-images.githubusercontent.com/5232626/201771139-3e0747e5-bd11-4ded-9e05-266a0360bf4b.mp4
